using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;

namespace LayoutFixer;

public enum HotkeyAction
{
    FullText,
    LastWord
}

public sealed class KeyboardHook : IDisposable
{
    private const int WH_KEYBOARD_LL = 13;
    private const int WM_KEYDOWN = 0x0100;
    private const int WM_KEYUP = 0x0101;
    private const int WM_SYSKEYDOWN = 0x0104;
    private const int WM_SYSKEYUP = 0x0105;
    private const uint LLKHF_INJECTED = 0x00000010;

    private readonly LowLevelKeyboardProc _callback;
    private readonly IntPtr _hook;

    private readonly HashSet<Keys> _pressed = new();
    private readonly HashSet<Keys> _suppressedKeys = new();
    private readonly object _typedWordLock = new();

    private string _typedWord = string.Empty;
    private IntPtr _typedWordWindow;
    private DateTime _typedWordAtUtc;

    private HotkeyAction? _pendingAction;
    private HashSet<Keys>? _pendingKeys;

    private string _fullTextHotkey = "Ctrl+Shift";
    private string _lastWordHotkey = "Insert";
    private HashSet<Keys> _fullTextKeys = HotkeyDefinition.Parse("Ctrl+Shift");
    private HashSet<Keys> _lastWordKeys = HotkeyDefinition.Parse("Insert");

    public event Action<HotkeyAction>? HotkeyPressed;

    public string FullTextHotkey
    {
        get => _fullTextHotkey;
        set
        {
            _fullTextHotkey = value;
            _fullTextKeys = HotkeyDefinition.Parse(value);
        }
    }

    public string LastWordHotkey
    {
        get => _lastWordHotkey;
        set
        {
            _lastWordHotkey = value;
            _lastWordKeys = HotkeyDefinition.Parse(value);
        }
    }

    public KeyboardHook()
    {
        _callback = HookCallback;

        using Process process = Process.GetCurrentProcess();
        using ProcessModule? module = process.MainModule;

        _hook = SetWindowsHookEx(
            WH_KEYBOARD_LL,
            _callback,
            GetModuleHandle(module?.ModuleName),
            0);

        if (_hook == IntPtr.Zero)
            throw new System.ComponentModel.Win32Exception(
                Marshal.GetLastWin32Error());
    }

    public bool TryGetLastTypedWord(IntPtr window, out string word)
    {
        lock (_typedWordLock)
        {
            if (window == IntPtr.Zero || window != _typedWordWindow ||
                string.IsNullOrEmpty(_typedWord) ||
                DateTime.UtcNow - _typedWordAtUtc > TimeSpan.FromSeconds(10))
            {
                word = string.Empty;
                return false;
            }

            word = _typedWord;
            return true;
        }
    }

    private IntPtr HookCallback(
        int nCode,
        IntPtr wParam,
        IntPtr lParam)
    {
        if (nCode < 0)
            return CallNextHookEx(
                _hook,
                nCode,
                wParam,
                lParam);

        var data =
            Marshal.PtrToStructure<KBDLLHOOKSTRUCT>(lParam);

        // Ignore keys generated by LayoutFixer itself.
        if ((data.flags & LLKHF_INJECTED) != 0)
            return CallNextHookEx(
                _hook,
                nCode,
                wParam,
                lParam);

        int message = wParam.ToInt32();

        bool down =
            message == WM_KEYDOWN ||
            message == WM_SYSKEYDOWN;

        bool up =
            message == WM_KEYUP ||
            message == WM_SYSKEYUP;

        if (!down && !up)
            return CallNextHookEx(
                _hook,
                nCode,
                wParam,
                lParam);

        Keys key = HotkeyDefinition.Normalize(
            (Keys)data.vkCode);

        if (down)
        {
            bool firstDown = _pressed.Add(key);

            if (firstDown && _pendingAction is null)
            {
                if (SetEquals(_pressed, _fullTextKeys))
                {
                    BeginPending(
                        HotkeyAction.FullText,
                        _fullTextKeys,
                        key);

                    return (IntPtr)1;
                }

                if (SetEquals(_pressed, _lastWordKeys))
                {
                    BeginPending(
                        HotkeyAction.LastWord,
                        _lastWordKeys,
                        key);

                    return (IntPtr)1;
                }
            }

            if (firstDown)
                TrackTypedKey(key, data);

            // Suppress auto-repeat of the key that completed
            // a recognized hotkey.
            if (_suppressedKeys.Contains(key))
                return (IntPtr)1;
        }

        if (up)
        {
            _pressed.Remove(key);

            bool suppress =
                _suppressedKeys.Remove(key);

            TryFirePending();

            if (suppress)
                return (IntPtr)1;
        }

        return CallNextHookEx(
            _hook,
            nCode,
            wParam,
            lParam);
    }

    private void TrackTypedKey(Keys key, KBDLLHOOKSTRUCT data)
    {
        if (IsCaretChangingKey(key) || HasCommandModifier())
        {
            ClearTypedWord();
            return;
        }

        if (key == Keys.Back)
        {
            lock (_typedWordLock)
            {
                if (_typedWord.Length > 0)
                    _typedWord = _typedWord[..^1];
                _typedWordAtUtc = DateTime.UtcNow;
            }
            return;
        }

        string typed = GetTypedText(data);
        if (string.IsNullOrEmpty(typed))
            return;

        IntPtr window = GetForegroundWindow();
        if (window == IntPtr.Zero)
            return;

        lock (_typedWordLock)
        {
            if (window != _typedWordWindow ||
                DateTime.UtcNow - _typedWordAtUtc > TimeSpan.FromSeconds(10))
                _typedWord = string.Empty;

            _typedWordWindow = window;
            foreach (char c in typed)
            {
                if (char.IsWhiteSpace(c))
                    _typedWord = string.Empty;
                else
                    _typedWord += c;
            }
            _typedWordAtUtc = DateTime.UtcNow;
        }
    }

    private static bool IsCaretChangingKey(Keys key) => key is
        Keys.Left or Keys.Right or Keys.Up or Keys.Down or Keys.Home or Keys.End or
        Keys.PageUp or Keys.PageDown or Keys.Delete or Keys.Return or Keys.Tab or Keys.Escape;

    private bool HasCommandModifier() =>
        _pressed.Contains(Keys.ControlKey) || _pressed.Contains(Keys.LControlKey) ||
        _pressed.Contains(Keys.RControlKey) || _pressed.Contains(Keys.Menu) ||
        _pressed.Contains(Keys.LMenu) || _pressed.Contains(Keys.RMenu) ||
        _pressed.Contains(Keys.LWin) || _pressed.Contains(Keys.RWin);

    private static string GetTypedText(KBDLLHOOKSTRUCT data)
    {
        var keyboardState = new byte[256];
        if (!GetKeyboardState(keyboardState))
            return string.Empty;

        IntPtr foreground = GetForegroundWindow();
        uint threadId = foreground == IntPtr.Zero ? 0 : GetWindowThreadProcessId(foreground, IntPtr.Zero);
        var buffer = new StringBuilder(8);
        int count = ToUnicodeEx(data.vkCode, data.scanCode, keyboardState, buffer, buffer.Capacity, 0,
            GetKeyboardLayout(threadId));
        return count > 0 ? buffer.ToString(0, count) : string.Empty;
    }

    private void ClearTypedWord()
    {
        lock (_typedWordLock)
        {
            _typedWord = string.Empty;
            _typedWordWindow = IntPtr.Zero;
            _typedWordAtUtc = DateTime.MinValue;
        }
    }

    private void BeginPending(
        HotkeyAction action,
        HashSet<Keys> keys,
        Keys completingKey)
    {
        _pendingAction = action;
        _pendingKeys = new HashSet<Keys>(keys);
        _suppressedKeys.Add(completingKey);
    }

    private void TryFirePending()
    {
        if (_pendingAction is null ||
            _pendingKeys is null)
        {
            return;
        }

        foreach (Keys key in _pendingKeys)
        {
            if (_pressed.Contains(key))
                return;
        }

        HotkeyAction action =
            _pendingAction.Value;

        _pendingAction = null;
        _pendingKeys = null;

        HotkeyPressed?.Invoke(action);
    }

    private static bool SetEquals(
        HashSet<Keys> current,
        HashSet<Keys> wanted)
    {
        return wanted.Count >= 1 &&
               wanted.Count <= HotkeyDefinition.MaxKeys &&
               current.SetEquals(wanted);
    }

    public void Dispose()
    {
        if (_hook != IntPtr.Zero)
            UnhookWindowsHookEx(_hook);
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct KBDLLHOOKSTRUCT
    {
        public uint vkCode;
        public uint scanCode;
        public uint flags;
        public uint time;
        public UIntPtr dwExtraInfo;
    }

    private delegate IntPtr LowLevelKeyboardProc(
        int nCode,
        IntPtr wParam,
        IntPtr lParam);

    [DllImport("user32.dll", SetLastError = true)]
    private static extern IntPtr SetWindowsHookEx(
        int idHook,
        LowLevelKeyboardProc lpfn,
        IntPtr hMod,
        uint dwThreadId);

    [DllImport("user32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static extern bool UnhookWindowsHookEx(
        IntPtr hhk);

    [DllImport("user32.dll")]
    private static extern IntPtr CallNextHookEx(
        IntPtr hhk,
        int nCode,
        IntPtr wParam,
        IntPtr lParam);

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    private static extern bool GetKeyboardState([Out] byte[] lpKeyState);

    [DllImport("user32.dll", CharSet = CharSet.Unicode)]
    private static extern int ToUnicodeEx(uint wVirtKey, uint wScanCode,
        byte[] lpKeyState, StringBuilder pwszBuff, int cchBuff, uint wFlags, IntPtr dwhkl);

    [DllImport("user32.dll")]
    private static extern IntPtr GetForegroundWindow();

    [DllImport("user32.dll")]
    private static extern uint GetWindowThreadProcessId(IntPtr hWnd, IntPtr lpdwProcessId);

    [DllImport("user32.dll")]
    private static extern IntPtr GetKeyboardLayout(uint idThread);

    [DllImport(
        "kernel32.dll",
        CharSet = CharSet.Auto,
        SetLastError = true)]
    private static extern IntPtr GetModuleHandle(
        string? lpModuleName);
}
