<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LayoutFixer</AssemblyName>
    <RootNamespace>LayoutFixer</RootNamespace>

    <Product>Layout Fixer</Product>
    <AssemblyTitle>Layout Fixer</AssemblyTitle>
    <Description>Keyboard layout text correction utility</Description>

    <Version>1.2.1</Version>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>1.2.1.0</FileVersion>
    <InformationalVersion>1.2.1</InformationalVersion>
    <ApplicationIcon>Assets\LayoutFixer.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\LayoutFixerLogo.png" />
  </ItemGroup>
</Project>
